fps
cpu_temp
gpu_temp
ram
vram
frame_timing
toggle_hud=Shift_R+F12

background_color=2E3440
background_alpha=0.85
text_color=D8DEE9
cpu_color=A3BE8C
gpu_color=88C0D0
ram_color=B48EAD
vram_color=81A1C1
frametime_color=8FBCBB
fps_color_1=A3BE8C
fps_color_2=EBCB8B
fps_color_3=BF616A
